# use version 3 of the docker compose syntax
version: '3'
services:
  # we named our first service 'web'
  web:
    # pass a hostname to the container (optinal)
    hostname: se.local
    
    # build a custom image 
    build:
      context: .
      dockerfile: .docker/Dockerfile
    
    # a name for easier reference
    image: se.local

    # map host port 8080 to container port 80
    ports:
        - 8080:80
    
    # volumes are like shared folders
    # container will see your local code changes
    volumes:
      - .:/var/www/html
    
    # first load the 'db' service 
    depends_on:
      - db

     #set the timezone
    environment:
      TZ: America/New_York
    
    # make 'db' a known service/host inside of 'web'
    # use this to make a mysql connection to host 'db'
    links:
      - db
  
  db:
    # use a default image
    image: mysql:5.7

    # restart on rebuild
    restart: always

    # again, port mapping 
    # e.g. to use Sequel Pro on our mac
    ports:
      - 13306:3306

    # backup data
    volumes:
        - ./mysql-data/db:/var/lib/mysql

    # the mysql image uses these to create database and users
    environment: 
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: se_database
      MYSQL_USER: seAdmin
      MYSQL_PASSWORD: test123